<?php

/**
* Implements hook_menu().
*/
function my_popup_menu() {
  $items['first-popup/%ctools_js'] = array(
    'title' => 'My first popup',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'page callback' => 'my_popup_callback',
    'type' => MENU_CALLBACK,
  );
  $items['first-popup'] = array(
    'title' => 'My first popup',
    'access callback' => TRUE,
    'page callback' => 'my_popup_page',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
* Popup’s example form.
*/
function id_example_form($form, $form_state) {
  $form = array();
  $form['some_text'] = array(
    '#title' => t('Some text'),
    '#type' => 'textfield',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('OK'),
  );
  return $form;
}


/**
* Popup’s callback function for form.
*/  
function my_popup_callback ($js = NULL) {
  if (!$js) {
      // Якщо JavaScript вимкнено — то виводимо форму без попапа.
    return drupal_get_form('id_example_form');
  }
  ctools_include('ajax');
  ctools_include('modal');
       // Задаємо початкові налаштування форми.
  $form_state = array(
    'ajax' => TRUE,
    'title' => t('Form title’'),
  );
  $output = ctools_modal_form_wrapper('id_example_form', $form_state);
  print ajax_render($output);
  drupal_exit();
}



/**
*Popup’s setings function.
*/
function my_ctools_popup_style() {
  static $added = FALSE;
  if ($added == FALSE) {
      $added = TRUE;
      // Підключаємо необхідні бібліотеки
      ctools_include('modal');
      ctools_include('ajax');
      ctools_modal_add_js();
      // Задаємо налаштування для попапа
      $popup_style = array(
          'first-popup-style' => array(
              'modalSize' => array(
                  'type' => 'fixed', // Тип попапа.
                  'width' => 475, // Ширина
                  'height' => 'auto', // Висота
                  'addHeight' => 700, // Максимальна висота
              ),
              'modalOptions' => array(
                  'opacity' => (float) 0.8, // Прозорість заднього фону
                  'background-color' => '#084b57', // Колір заднього фону
              ),
              'closeText' => '', // Текст для кнопки «close»
              'loadingText' => '', // Текст при завантаженні попапа
              'animation' => 'fadeIn', // Тип анімації
              'modalTheme' => 'my_custom_theme', // Назва теми, яку слід підключити
              'animationSpeed' => 'fast', // Швидкість анімації попапа
          ),
      );
      drupal_add_js($popup_style, 'setting'); // Підключаємо налаштування
      ctools_add_js('my_popup_style.js', 'my_popup'); // Підключаємо тему (перший параметр – це назва файла теми, другий - назва модуля, в якому цей файл знаходиться)
  }
}

function my_popup_page() {
  // Підключаємо функцію з налаштуваннями.
  my_ctools_popup_style();
  // Задаємо налаштування для лінка.
  $link = array(
    '#type' => 'link',
    '#title' => t('Popup link'),
    '#href' => 'first-popup/nojs',
    '#attributes' => array('class' => array('ctools-use-modal', 'ctools-modal-first-popup-style')),
  );
// Виводимо лінк
  return drupal_render($link);
}