<?php

/**
* Implements hook_menu().
*/
function my_popup_menu() {
  $items['node/%nid/%ctools_js'] = array(
    'title' => 'My first popup',
    'page arguments' => array(1, 2),
    'access callback' => TRUE,
    'page callback' => 'my_popup_callback',
    'type' => MENU_CALLBACK,
  );
  $items['node/%nid'] = array(
    'title' => 'My first popup',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'page callback' => 'my_popup_page',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
* Popup’s example form.
*/
function id_example_form($form, $form_state) {
  $form = array();
  $form['some_text'] = array(
    '#title' => t('Some text'),
    '#type' => 'textfield',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('OK'),
  );
  return $form;
}


/**
* Popup’s callback function for form.
*/  
function my_popup_callback ($nid, $js = NULL) {
  if (!$js) {
    // Якщо JavaScript вимкнено — то виводимо форму без попапа.
    return drupal_get_form('id_example_form');
  }
    ctools_include('ajax');
    ctools_include('modal');
    ctools_modal_add_js();
  // Задаємо початкові налаштування форми.
  $webFormNode = node_load($nid);
  dsm($webFormNode);
  $form_state = array(
    'ajax' => TRUE,
    'title' => t('Form title'),
  );
  $output = ctools_modal_form_wrapper('comment_node_article_form', $form_state);
  print ajax_render($output);
  drupal_exit();
}



/**
*Popup’s setings function.
*/
function my_ctools_popup_style() {
  static $added = FALSE;
  if ($added == FALSE) {
    $added = TRUE;
    ctools_include('ajax');
    ctools_include('modal');
    ctools_modal_add_js();
    $popup_style = array(
      'popup-style' => array(
        'modalSize' => array(
          'type' => 'fixed',
          'width' => 675, 
          'height' => 700, 
          // 'addHeight' => 700,
        ),
        'modalOptions' => array(
          'opacity' => 0.8, 
          'background-color' => '#084b57',
        ),
        'closeText' => 'Close', // Текст для кнопки «close»
        'loadingText' => 'Wait', // Текст при завантаженні попапа
        'animation' => 'fadeIn', // Тип анімації
        'modalTheme' => 'my_popup_style', // Назва теми, яку слід підключити
        'animationSpeed' => 'fast', // Швидкість анімації попапа
      ),
    );
    drupal_add_js($popup_style, 'setting'); // Підключаємо налаштування
    ctools_add_js('my-popup-style', 'my_popup'); 
    // Підключаємо тему (перший параметр – це назва файла теми, другий - назва модуля, в якому цей файл знаходиться)
  }
}

function my_popup_page($nid) {
  dsm($nid);
  // Підключаємо функцію з налаштуваннями.
  my_ctools_popup_style();
  // Задаємо налаштування для лінка.
  $href = '/node/' . $nid . '/nojs';
  $link = array(
    '#type' => 'link',
    '#title' => t('Popup link'),
    '#href' => $href,
    '#attributes' => array('class' => array('ctools-use-modal',  'ctools-modal-popup-style')),
  );
  // Виводимо лінк
  return drupal_render($link);
}

/**
 * Implements hook_form_alter().
 */
function my_popup_form_alter(&$form, &$form_state, $form_id) {
  dsm($form);
  dsm($form_state);
  dsm($form_id);
}