<?php
/**
 * @file
 * Install, update, and uninstall functions for the mentor_vimeo module.
 */

/**
 * Implements hook_field_schema().
 */
function mentor_vimeo_field_schema($field) {
  $columns = array(
    'mentor_vimeo_field' => array(
      'type' => 'int',
      'unsigned' => TRUE, 
      'not null' => TRUE,
    ),
  );
  $indexes = array(
    'mentor_vimeo_field' => array('mentor_vimeo_field'),
  );
  return array(
    'columns' => $columns,
    'indexes' => $indexes,
  );
}
