<?php

/**
	* Implements hook_menu()
	*/
function mentor_menu() {
	$items = array();
	$items['static-example'] = array(
		'title'            => 'Static example',
		'page callback'    => 'mentor_callback',
		'access callback'  => TRUE,
	);
	return $items;
}

/**
 * Build form function.
 */
function mentor_counter($start = 0) {
	$call_count = &drupal_static(__FUNCTION__);
  if (!isset($call_count[$start])) {
    $call_count[$start] = $start;
  }
  $call_count[$start]++;
	return $call_count[$start];
}

function mentor_callback() {
	drupal_set_message(mentor_counter(10));
	
  for ($i = 1; $i <= 99; $i++) {
		mentor_counter();
	}
	drupal_set_message(mentor_counter());

	mentor_counter(10);
	drupal_set_message(mentor_counter(10));
	return '';
}

